In [2]:
import torch
a = torch.ones(3)
print(a)
print(a[2])
print(float(a[2]))
a[2] = 2.0
print(a)

tensor([1., 1., 1.])
tensor(1.)
1.0
tensor([1., 1., 2.])


In [10]:
points = torch.zeros(3)
points[0] = 3.0
points[1] = 2.0
points[2] = 1.0
print(points)
points = torch.tensor([1,2,3])
print(points)
points = torch.tensor([[1.,2.],[3.,4.],[5.,6.]])
print(points)
print(points.shape)
print(points.size())

tensor([3., 2., 1.])
tensor([1, 2, 3])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])
torch.Size([3, 2])


In [5]:
points = torch.tensor([[1.,2.],[3.,4.],[5.,6.]])
print(points.storage())  #张量中的所有元素
second_point = points[2]
print(second_point.storage_offset())   #元素在张量中的位置
third_point = points[1][1]
forth_point = second_point[1]
print(third_point.storage_offset())
print(forth_point.storage_offset())
another_point = points[1].clone()
print(another_point.storage_offset())

print(points.stride())   #每个维度变一下，对应要在内存跳多长

points_t = points.t()    #转置矩阵
print(points_t)
print(points_t.stride())

 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
[torch.FloatStorage of size 6]
4
3
5
0
(2, 1)
tensor([[1., 3., 5.],
        [2., 4., 6.]])
(1, 2)


In [8]:
some_t = torch.ones(3,4,5)
print(some_t.stride())
transpose_t = some_t.transpose(0,2)    #把0维和2维做替换
print(transpose_t.shape)
print(transpose_t.stride())
print(some_t.is_contiguous())    #在内存里是否连续
print(transpose_t.is_contiguous())

(20, 5, 1)
torch.Size([5, 4, 3])
(1, 5, 20)
True
False


In [13]:
double_points = torch.ones(5,2,dtype=torch.double)
short_points = torch.tensor([[1,2],[3,4]],dtype=torch.short)
print(double_points)
print(short_points)
print(short_points.double())
rand_points = torch.rand(4,3,dtype=torch.double)  #只能随机生成小数
print(rand_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 2],
        [3, 4]], dtype=torch.int16)
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([[0.3696, 0.3512, 0.0192],
        [0.9012, 0.9574, 0.4486],
        [0.6438, 0.0635, 0.3628],
        [0.7502, 0.9651, 0.5680]], dtype=torch.float64)


In [15]:
double_points = torch.ones(2,2,dtype=torch.double)
short_points = torch.tensor([[1,2],[3,4]],dtype=torch.short)
print(double_points * short_points)   #点乘，对应元素相乘

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [3]:
points = torch.tensor([[4.,1.],[5.,3.],[2.,1.]])
print(points[1:,0])
print(points[None])

tensor([5., 2.])
torch.Size([1, 3, 2])


In [11]:
points = torch.ones(3,4)
points_np = points.numpy()
print(points_np)
points = torch.from_numpy(points_np)
print(points)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [3]:
points = torch.ones(3,4)
torch.save(points,'/home/zhengyuheng/Code/PythonLearning/Pytorch/Deep  Learning  with  Pytorch/save.t')
P = torch.load('/home/zhengyuheng/Code/PythonLearning/Pytorch/Deep  Learning  with  Pytorch/save.t')
print(P)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
