In [28]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])
print(x + y, x * y, x / y, x**y,"\n")

x = torch.arange(4)
print(x,"\n")
print(len(x),x.shape,"\n")

A = torch.arange(20).reshape(5, 4)
print(A,"\n",A.T,"\n")

B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(B,"\n",B==B.T,"\n")

X = torch.arange(24).reshape(2, 3, 4)
print(X)

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
print(A,"\n",A+B,"\n")
print(A * B)

a = 2
X = torch.arange(24).reshape(2, 3, 4)
print(a + X,"\n", (a * X).shape,"\n")

x = torch.arange(4, dtype=torch.float32)
print(x, x.sum())

print(A,A.shape, A.sum())
A_sum_axis0 = A.sum(axis=0)   #对第0维度求和,即把第0维度消除
print(A_sum_axis0, A_sum_axis0.shape)
A_sum_axis1 = A.sum(axis=1)   #对第1维度求和,即把第1维度消除
print(A_sum_axis1, A_sum_axis1.shape)
print(A.sum(axis=[0, 1]))# Same as `A.sum()`

#求均值
print(A.mean(),"\n", A.sum() / A.numel(),"\n")
print(A.mean(axis=0),"\n", A.sum(axis=0) / A.shape[0],"\n")

#保留维度求和
sum_A = A.sum(axis=1, keepdims=True)
print(sum_A)
print(A / sum_A)   #做广播运算

y = torch.ones(4, dtype=torch.float32)
print(x, y, torch.dot(x, y))

#矩阵乘向量
print(A.shape, x.shape, torch.mv(A, x))
#矩阵乘矩阵
B = torch.ones(4, 3)
print(torch.mm(A, B))

#二范数
u = torch.tensor([3.0, -4.0])
print(torch.norm(u))
#一范数
print(torch.abs(u).sum())

tensor([5.]) tensor([6.]) tensor([1.5000]) tensor([9.]) 

tensor([0, 1, 2, 3]) 

4 torch.Size([4]) 

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]) 
 tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]]) 

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]]) 
 tensor([[True, True, True],
        [True, True, True],
        [True, True, True]]) 

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) 
 tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]]) 

tensor([[  0.,   1.,   4